<%@ Page Title="" Language="C#" MasterPageFile="~/Main.master" AutoEventWireup="true" CodeFile="MaterialView.aspx.cs" Inherits="MaterialView" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">


     <asp:UpdatePanel ID="Upanel" runat="server" UpdateMode="Conditional">
    <ContentTemplate>
    <div align="center">
 <div id="wrapper">
    <div id="page-wrapper7">
    <div class="row">
                <div class="col-lg-12">
                    <div class="panel panel-primary">
                        <div class="panel-heading">
                            <h3 class="panel-title">Material View</h3>
                        </div>
                        <div class="panel-body">
                        
                            
                            
                            <div  style="overflow:scroll; height:370px; width:737px; background-color:White">
                   <asp:GridView ID="grdMaterialView" runat="server" AllowPaging="true" Font-Size="Medium"
                       AutoGenerateColumns="False" PageSize="50000" CssClass="Grid" PagerStyle-CssClass="pgr"
                        AlternatingRowStyle-CssClass="alt" EmptyDataText="No Such Data Found" 
                           DataKeyNames="ID" AllowSorting="True" AutoGenerateDeleteButton="True" 
                           AutoGenerateEditButton="True" 
                           onrowcancelingedit="grdMaterialView_RowCancelingEdit" 
                           onrowdatabound="grdMaterialView_RowDataBound" 
                           onrowdeleting="grdMaterialView_RowDeleting" 
                           onrowediting="grdMaterialView_RowEditing" 
                           onrowupdating="grdMaterialView_RowUpdating">
                                           
                        <Columns>
                             <asp:TemplateField HeaderText="SNo">
                                  <ItemTemplate>
                                      <%#Container.DataItemIndex+1 %>
                                  </ItemTemplate>
                              </asp:TemplateField>

                        
                         <asp:TemplateField HeaderText="ID" Visible="false">
                          <ItemTemplate>
                          <asp:Label id="lblId" runat="server" Text='<%#Eval("ID")%>'></asp:Label>
                          </ItemTemplate>
                          </asp:TemplateField>
                        
                        
                        
                          <asp:TemplateField HeaderText="Material Name">
                          <ItemTemplate>
                          <asp:Label id="lblMaterialName" runat="server" Text='<%#Eval("MATERIALNAME")%>'></asp:Label>
                          </ItemTemplate>
                          <EditItemTemplate>
                          <asp:TextBox ID="txtMaterialName" runat="server" Text='<%#Eval("MATERIALNAME")%>'></asp:TextBox>
                          
                          </EditItemTemplate>
                          </asp:TemplateField>
                          
                          <asp:TemplateField HeaderText="HSNCODE">
                          <ItemTemplate>
                          <asp:Label id="lblHsncode" runat="server" Text='<%#Eval("HSNCODE")%>'></asp:Label>
                          </ItemTemplate>
                          <EditItemTemplate>
                          <asp:TextBox ID="txtHsncode" runat="server" Text='<%#Eval("HSNCODE")%>'></asp:TextBox>
                          
                          </EditItemTemplate>
                          </asp:TemplateField>
                          
               
                             
                          
                         <%-- <asp:TemplateField HeaderText="Remove" ItemStyle-Width="30px">
                            <ItemTemplate>
                            <asp:ImageButton id="btnItemRemove"   ImageUrl="~/images/Alarm-Error-icon.png" width="20px" runat="server" CommandArgument='<%#Eval("VENDORID") %>' CommandName="REMOVE"></asp:ImageButton>
                            </ItemTemplate>
                            <ItemStyle Width="30px" />
                           </asp:TemplateField>         --%> 
                        </Columns>
                                     
                        <PagerStyle CssClass="pgr" />
                        <AlternatingRowStyle CssClass="alt" />
                   
                  </asp:GridView>
                  </div>
                            
                            
                            
                            
                        </div>
                    </div>
                </div>
            </div>
            
        
        </div>
   </div>
   </div>
     </ContentTemplate>
     </asp:UpdatePanel>
</asp:Content>

