<%@ Page Language="C#" MasterPageFile="~/Main.master" AutoEventWireup="true" CodeFile="VendorMasterView.aspx.cs" Inherits="VendorMasterView" Title="Vendor Master View Page" %>
<%@ Register Assembly="AjaxControlToolkit" TagPrefix="asp" Namespace="AjaxControlToolkit"%>
<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
 <link href="Gridstyle.css" rel="stylesheet" type="text/css" />

</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
  <asp:UpdatePanel ID="Upanel" runat="server" UpdateMode="Conditional">
  <ContentTemplate>
<br />
<div align="center">
<div id="wrapper">
    <div id="page-wrapper7">
    <div class="row">
                <div class="col-lg-12">
                    <div class="panel panel-primary">
                        <div class="panel-heading">
                            <h3 class="panel-title">VendorMaster View</h3>
                        </div>
                        <div class="panel-body">
                        
                            
                            
                            <div  style="overflow:scroll; height:370px; width:737px; background-color:White">
                   <asp:GridView ID="grdVendorMasterView" runat="server" AllowPaging="true" Font-Size="Small"
                       AutoGenerateColumns="False" PageSize="50000" CssClass="Grid" PagerStyle-CssClass="pgr"
                        AlternatingRowStyle-CssClass="alt" EmptyDataText="No Such Data Found" 
                           DataKeyNames="VID" AllowSorting="True" AutoGenerateDeleteButton="True" 
                           AutoGenerateEditButton="True" 
                           onrowcancelingedit="grdVendorMasterView_RowCancelingEdit" 
                           onrowdatabound="grdVendorMasterView_RowDataBound" 
                           onrowdeleting="grdVendorMasterView_RowDeleting" 
                           onrowediting="grdVendorMasterView_RowEditing" 
                           onrowupdating="grdVendorMasterView_RowUpdating">
                                           
                        <Columns>
                        
                              <asp:TemplateField HeaderText="SNo">
                                  <ItemTemplate>
                                      <%#Container.DataItemIndex+1 %>
                                  </ItemTemplate>
                              </asp:TemplateField>


                        <asp:TemplateField HeaderText="VendorId" Visible="false">
                          <ItemTemplate>
                          <asp:Label id="lblVId" runat="server" Text='<%#Eval("VID")%>'></asp:Label>
                          </ItemTemplate>
                          </asp:TemplateField>
                          
                        
                        
                          <asp:TemplateField HeaderText="VendorName">
                          <ItemTemplate>
                          <asp:Label id="lblVendorName" runat="server" Text='<%#Eval("VENDORNAME")%>'></asp:Label>
                          </ItemTemplate>
                          <EditItemTemplate>
                          <asp:TextBox ID="txtVendorName" runat="server" Text='<%#Eval("VENDORNAME")%>'></asp:TextBox>
                          
                          </EditItemTemplate>
                          </asp:TemplateField>
                          
                          <asp:TemplateField HeaderText="Authority">
                          <ItemTemplate>
                          <asp:Label id="lblAuthority" runat="server" Text='<%#Eval("AUTHORITYNAME")%>'></asp:Label>
                          </ItemTemplate>
                          <EditItemTemplate>
                          <asp:TextBox ID="txtAuthority" runat="server" Text='<%#Eval("AUTHORITYNAME")%>'></asp:TextBox>
                          
                          </EditItemTemplate>
                          </asp:TemplateField>
                             
                          <asp:TemplateField HeaderText="Addr1">
                          <ItemTemplate>
                          <asp:Label id="lblAddr1" runat="server" Text='<%#Eval("ADDR1")%>'></asp:Label>
                          </ItemTemplate>
                          <EditItemTemplate>
                          <asp:TextBox ID="txtAddr1" runat="server" Text='<%#Eval("ADDR1")%>'></asp:TextBox>
                          
                          </EditItemTemplate>
                          </asp:TemplateField>
                          
                         <asp:TemplateField HeaderText="Addr2">
                          <ItemTemplate>
                          <asp:Label id="lblAddr2" runat="server" Text='<%#Eval("ADDR2")%>'></asp:Label>
                          </ItemTemplate>
                          <EditItemTemplate>
                          <asp:TextBox ID="txtAddr2" runat="server" Text='<%#Eval("ADDR2")%>'></asp:TextBox>
                          
                          </EditItemTemplate>
                          </asp:TemplateField>
                          
                          <asp:TemplateField HeaderText="Place">
                          <ItemTemplate>
                          <asp:Label id="lblPlace" runat="server" Text='<%#Eval("PLACE")%>'></asp:Label>
                          </ItemTemplate>
                          <EditItemTemplate>
                          <asp:TextBox ID="txtPlace" runat="server" Text='<%#Eval("PLACE")%>'></asp:TextBox>
                          
                          </EditItemTemplate>
                          </asp:TemplateField>
                          
                           <asp:TemplateField HeaderText="Pincode">
                          <ItemTemplate>
                          <asp:Label id="lblPinCode" runat="server" Text='<%#Eval("PINCODE")%>'></asp:Label>
                          </ItemTemplate>
                          <EditItemTemplate>
                          <asp:TextBox ID="txtPinCode" runat="server" Text='<%#Eval("PINCODE")%>'></asp:TextBox>
                          
                          </EditItemTemplate>
                          </asp:TemplateField>
                          
                       
                         <%-- <asp:TemplateField HeaderText="Remove" ItemStyle-Width="30px">
                            <ItemTemplate>
                            <asp:ImageButton id="btnItemRemove"   ImageUrl="~/images/Alarm-Error-icon.png" width="20px" runat="server" CommandArgument='<%#Eval("VENDORID") %>' CommandName="REMOVE"></asp:ImageButton>
                            </ItemTemplate>
                            <ItemStyle Width="30px" />
                           </asp:TemplateField>         --%> 
                        </Columns>
                                     
                        <PagerStyle CssClass="pgr" />
                        <AlternatingRowStyle CssClass="alt" />
                   
                  </asp:GridView>
                  </div>
                            
                            
                            
                            
                        </div>
                    </div>
                </div>
            </div>
            
        
        </div>
   </div>
   </div>
</ContentTemplate>
</asp:UpdatePanel>
</asp:Content>
